#include "src/game/envfx_snow.h"

const GeoLayout ssl_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ssl_dl_15_GeoRoot_ssl_2_ssl_seg7_dl_0701EE80_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ssl_dl_15_GeoRoot_ssl_2_ssl_seg7_dl_0701EE80_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 0, ssl_dl_16_GeoRoot_ssl_2_ssl_seg7_dl_0701F920_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 90, 0, 0, ssl_dl_17_GeoRoot_ssl_2_ssl_seg7_dl_0701FCE0_mesh_layer_6),
		GEO_ASM(MOVTEX_SSL_SAND_PIT_PYRAMID, geo_movtex_update_horizontal),
		GEO_ASM(0, geo_movtex_pause_control),
		GEO_ASM(MOVTEX_PYRAMID_SAND_PATHWAY_FRONT, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_PYRAMID_SAND_PATHWAY_FLOOR, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_PYRAMID_SAND_PATHWAY_SIDE, geo_movtex_draw_nocolor),
		GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ssl_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_CLOSE, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ssl_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
