#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ssl/header.h"

#include "levels/ssl/areas/1/5/geo.inc.c"
#include "levels/ssl/areas/2/4/geo.inc.c"
#include "levels/ssl/pyramid_top/geo.inc.c"
#include "levels/ssl/tox_box/geo.inc.c"
#include "levels/ssl/areas/1/geo.inc.c"
#include "levels/ssl/grindel/geo.inc.c"
#include "levels/ssl/spindel/geo.inc.c"
#include "levels/ssl/moving_pyramid_wall/geo.inc.c"
#include "levels/ssl/pyramid_elevator/geo.inc.c"
#include "levels/ssl/areas/2/geo.inc.c"
#include "levels/ssl/areas/3/geo.inc.c"

#include "levels/ssl/geo.inc.c"
#include "levels/ssl/ssl_pyramid_top_custom/geo.inc.c"
#include "levels/ssl/ssl_snow_pit/geo.inc.c"
#include "levels/ssl/ssl_tox_box_fog/geo.inc.c"
#include "levels/ssl/snow_tree_fog/geo.inc.c"
#include "levels/ssl/pokey_with_fog/geo.inc.c"
#include "levels/ssl/pokey_head_with_fog/geo.inc.c"
#include "levels/ssl/ssl_pryamid_wall_custom/geo.inc.c"
#include "levels/ssl/ssl_pryamid_walL_custom/geo.inc.c"
#include "levels/ssl/ssl_pryamid_elevator_custom/geo.inc.c"