#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ccm_dl_15_GeoRoot_ccm_2_ccm_seg7_dl_0701CE30_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ccm_dl_16_GeoRoot_ccm_2_ccm_seg7_dl_0701E558_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE_DECAL, 90, 0, 0, ccm_dl_17_GeoRoot_ccm_2_ccm_seg7_dl_0701E6B0_mesh_layer_2),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 0, ccm_dl_18_GeoRoot_ccm_2_ccm_seg7_dl_0701FC78_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 0, ccm_dl_19_GeoRoot_ccm_2_ccm_seg7_dl_0701FD78_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_TRANSPARENT, 90, 0, 0, ccm_dl_20_GeoRoot_ccm_2_ccm_seg7_dl_0701FE60_mesh_layer_5),
		GEO_ROTATION_NODE_WITH_DL(LAYER_TRANSPARENT, 90, 0, 0, ccm_dl_21_GeoRoot_ccm_2_ccm_seg7_dl_070207F0_mesh_layer_5),
		GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_FLAMING_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_SLIDE_HOOT, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
