#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "chao/geo.inc.c"
#include "kart/geo.inc.c"
#include "mario_billboard/geo.inc.c"
#include "bobomb_cop/geo.inc.c"
#include "heave_ho/geo.inc.c"
#include "item_box/geo.inc.c"
#include "chain_chomp/geo.inc.c"
#include "chain_ball/geo.inc.c"
#include "thwomp/geo.inc.c"
#include "shadow_mario/geo.inc.c"
#include "spring/geo.inc.c"
#include "skeeter/geo.inc.c"
#include "koopa_shell/geo.inc.c"
#include "cat_normal/geo.inc.c"
#include "cat_loaf/geo.inc.c"
#include "betah_mario_icon/geo.inc.c"
#include "moneybag/geo.inc.c"
#include "levels/rr/flying_carpet/geo.inc.c"
#include "king_bobomb/geo.inc.c"
#include "bowser/geo.inc.c"
#include "bowser_flame/geo.inc.c"
#include "impact_ring/geo.inc.c"
#include "yellow_sphere/geo.inc.c"
#include "bomb/geo.inc.c"
#include "impact_smoke/geo.inc.c"

#include "armstrong_frame_1/geo.inc.c"
#include "armstrong_frame_2/geo.inc.c"
#include "armstrong_frame_3/geo.inc.c"
#include "armstrong_idle/geo.inc.c"