extern const GeoLayout armstrong_frame_2_geo[];
extern u8 armstrong_frame_2_armstrong_frame_2_rgba16_rgba16[];
extern Vtx armstrong_frame_2_armstrong_frame_2_mesh_layer_4_vtx_cull[8];
extern Vtx armstrong_frame_2_armstrong_frame_2_mesh_layer_4_vtx_0[64];
extern Gfx armstrong_frame_2_armstrong_frame_2_mesh_layer_4_tri_0[];
extern Gfx mat_armstrong_frame_2_armstrong_frame_2[];
extern Gfx mat_revert_armstrong_frame_2_armstrong_frame_2[];
extern Gfx armstrong_frame_2_armstrong_frame_2_mesh_layer_4[];
