#include "src/game/envfx_snow.h"

const GeoLayout ssl_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ssl_dl_15_GeoRoot_ssl_1_ssl_seg7_dl_07009F48_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, ssl_dl_16_GeoRoot_ssl_1_ssl_seg7_dl_0700BA78_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 0, ssl_dl_17_GeoRoot_ssl_1_ssl_seg7_dl_0700BC18_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 90, 0, 0, ssl_dl_18_GeoRoot_ssl_1_ssl_seg7_dl_0700BD00_mesh_layer_6),
		GEO_ASM(MOVTEX_SSL_SAND_PIT_OUTSIDE, geo_movtex_update_horizontal),
		GEO_ASM(0, geo_movtex_pause_control),
		GEO_ASM(SSL_MOVTEX_PUDDLE_WATER, geo_movtex_draw_water_regions),
		GEO_ASM(SSL_MOVTEX_TOXBOX_QUICKSAND_MIST, geo_movtex_draw_water_regions),
		GEO_ASM(MOVTEX_SSL_PYRAMID_SIDE, geo_movtex_draw_colored),
		GEO_ASM(MOVTEX_SSL_PYRAMID_CORNER, geo_movtex_draw_colored),
		GEO_ASM(MOVTEX_SSL_COURSE_EDGE, geo_movtex_draw_colored),
		GEO_ASM(0, geo_cannon_circle_base),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ssl_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0xB639),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_RADIAL, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ssl_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_BLIZZARD, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
