#include "anim_rekt_by_kart.inc.c"
#include "anim_on_kart_idle.inc.c"
#include "anim_on_kart_turn_left.inc.c"
#include "anim_on_kart_left_idle.inc.c"
#include "anim_on_kart_turn_right.inc.c"
#include "anim_on_kart_right_idle.inc.c"
#include "anim_get_coin.inc.c"
