#include "src/game/envfx_snow.h"

const GeoLayout ttm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -47, 171, ttm_dl_15_GeoRoot_ttm_1_ttm_seg7_dl_0700A120_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, -47, 171, 95, 0, 0, ttm_dl_16_GeoRoot_ttm_1_ttm_seg7_dl_0700A2E0_mesh_layer_1),
		GEO_ASM(0, geo_painting_update),
		GEO_ASM(PAINTING_ID(0, 2), geo_painting_draw),
		GEO_ASM(0, geo_movtex_pause_control),
		GEO_ASM(MOVTEX_TTM_BEGIN_WATERFALL, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_TTM_END_WATERFALL, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_TTM_BEGIN_PUDDLE_WATERFALL, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_TTM_END_PUDDLE_WATERFALL, geo_movtex_draw_nocolor),
		GEO_ASM(MOVTEX_TTM_PUDDLE_WATERFALL, geo_movtex_draw_nocolor),
		GEO_ASM(TTM_MOVTEX_PUDDLE, geo_movtex_draw_water_regions),
		GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
		GEO_ASM(0, geo_cannon_circle_base),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ttm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_RADIAL, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ttm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
