#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, bbh_dl_15_GeoRoot_castle_courtyard_1_castle_courtyard_seg7_dl_070048B8_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_15_GeoRoot_castle_courtyard_1_castle_courtyard_seg7_dl_070048B8_mesh_layer_6),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_15_GeoRoot_castle_courtyard_1_castle_courtyard_seg7_dl_070048B8_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_15_GeoRoot_castle_courtyard_1_castle_courtyard_seg7_dl_070048B8_mesh_layer_2),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_15_GeoRoot_castle_courtyard_1_castle_courtyard_seg7_dl_070048B8_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_ASM(0, geo_movtex_pause_control),
		GEO_ASM(CASTLE_COURTYARD_MOVTEX_STAR_STATUE_WATER, geo_movtex_draw_water_regions),
		GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, bbh_dl_fountain_visual_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 0, bbh_dl_gate_gfx_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -23, 0, -30, bbh_dl_tree_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 1276, 0, 1813, bbh_dl_tree_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -450, 0, 3889, bbh_dl_tree_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 852, 0, 6398, bbh_dl_tree_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 3849, 0, 9645, bbh_dl_tree_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8592, 922, 10784, bbh_dl_tree_005_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 16012, 922, 10806, bbh_dl_tree_006_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 19851, 0, 9236, bbh_dl_tree_007_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 23052, 0, 6025, bbh_dl_tree_008_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 24825, 0, 2936, bbh_dl_tree_009_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 22545, 0, 3327, bbh_dl_tree_010_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 23348, 0, -733, bbh_dl_tree_011_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 21574, 0, -3936, bbh_dl_tree_012_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 15993, 922, -6649, bbh_dl_tree_013_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8557, 922, -6611, bbh_dl_tree_014_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 4926, 0, -4898, bbh_dl_tree_015_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 120, 36000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
